spring:
  application:
    name: msclient

server:
  port: 0
  wait-time-in-ms-when-sync-empty: 0

eureka:
  client:
    service-url:
      defaultZone: http://system:stymssme@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
